boilerplate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import os
from hydro.urls import status_api_patterns
from hydro.views import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'hydro'),
)

handler403 = 'hydro.templates.permission_denied_view'

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^status/', include(status_api_patterns)),
    url(r'^hydro/home', HomeView, name="home"),
    url(r'^error', ErrorView, name="error"),
]

hydro/urls.py
import os
from django.conf.urls import include, url
from rest_framework import routers
from hydro.api import *
from hydro.views import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'hydro'),
)

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'data', DataViewSet)
router.register(r'data', DataTypeViewSet)

hydro_patterns = [
    url(r'^home', HomeView, name="home"),
    url(r'^chemical', ChemicalSettingsView.as_view(), name="chemical"),
    url(r'^waste', WasteSettingsView.as_view(), name="waste"),
    url(r'^control', ControlEditView, name="control"),
    url(r'^error', ErrorView, name="error"),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

hydroponics/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import os
from hydro.urls import hydro_patterns
from hydro.views import *

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'hydro'),
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^hydro/', include(hydro_patterns)),
]

hydro/models.py
from django.db import models
import django.utils.timezone as tz


class Data(models.Model):
    def __str__(self):
        return str(self.type) + ": " + str(self.value) + " on: " + str(self.date_time)

    date_time = models.DateTimeField(blank=False)
    type = models.ForeignKey('DataType', blank=False, on_delete=True)
    value = models.FloatField(blank=True, null=True)


class DataType(models.Model):
    def __str__(self):
        return str(self.type)

    type = models.CharField(max_length=20, blank=False)


class RequestType(models.Model):
    def __str__(self):
        return str(self.type)

    type = models.CharField(max_length=20, blank=False)


class Status(models.Model):
    def __str__(self):
        return str(self.status)

    status = models.CharField(max_length=20, blank=False)


DEFAULT_STATUS_ID = 1


class Request(models.Model):
    def __str__(self):
        return str(self.type) + " on: " + str(self.request_time)

    request_time = models.DateTimeField(blank=True, default=tz.now)
    exec_time = models.DateTimeField(blank=True, null=True)
    type = models.ForeignKey('RequestType', blank=False, on_delete=True)
    status = models.ForeignKey('Status', default=DEFAULT_STATUS_ID, blank=False, on_delete=True)
    arg1 = models.FloatField(blank=True, null=True)
    arg2 = models.FloatField(blank=True, null=True)


class ChemicalSettings(models.Model):
    # PH REGULATION
    auto_regulate_pH = models.BooleanField(default=False, blank=False)
    low_pH = models.FloatField(blank=False)
    high_pH = models.FloatField(blank=False)
    pH_adj_volume = models.FloatField(blank=False)
    last_pH_change = models.DateTimeField(null=True, blank=True)

    # NUTRIENT REGULATION
    auto_regulate_nutrients = models.BooleanField(default=False, blank=False)
    low_EC = models.FloatField(blank=False)
    high_EC = models.FloatField(blank=False)
    nutrient_adj_volume = models.FloatField(blank=False)
    last_nutrient_change = models.DateTimeField(null=True, blank=True)

    # ORP REGULATION
    auto_regulate_ORP = models.BooleanField(default=False, blank=False)
    low_ORP = models.FloatField(blank=False)
    high_ORP = models.FloatField(blank=False)
    ORP_adj_volume = models.FloatField(blank=False)
    last_ORP_change = models.DateTimeField(null=True, blank=True)

    # DATA
    change_rate = models.DurationField(null=True, blank=True)
    last_poll = models.DateTimeField(null=True, blank=True)
    polling_rate = models.DurationField(null=True, blank=True)
    minimum_data_count = models.IntegerField(default=100, blank=False)


class WasteSettings(models.Model):
    # WASTE REGULATION
    auto_water_change = models.BooleanField(default=False, blank=False)
    last_water_change = models.DateTimeField(null=True, blank=True)
    maximum_water_change_interval = models.IntegerField(null=True, blank=True)
    minimum_water_change_interval = models.IntegerField(null=True, blank=True)

    # WATER REGULATION
    auto_pump = models.BooleanField(default=False, blank=False)
    auto_refill = models.BooleanField(default=False, blank=False)
    reservoir_volume = models.IntegerField(default=27, blank=False)  # liters
    basin_volume = models.IntegerField(default=27, blank=False)  # liters

hydro/forms.py
from django import forms
from hydro.models import *


class ChemicalSettingsForm(forms.ModelForm):
    """Form for editing chemical chemical_settings from POST requests

        """
    class Meta:
        model = ChemicalSettings
        exclude = ['last_pH_change', 'last_nutrient_change', 'last_ORP_change']


class WasteSettingsForm(forms.ModelForm):
    """Form for editing waste chemical_settings from POST requests

        """
    class Meta:
        model = WasteSettings
        exclude = ['last_water_change']


class RequestForm(forms.ModelForm):
    """Form for creating action requests from POST requests

        """
    class Meta:
        model = Request
        exclude = ['exec_time', 'request_time', 'status']

hydro/views.py
from django.shortcuts import render, redirect
from hydro.forms import *
from hydro.serializers import *
from django.views.generic.edit import FormView
from django.forms.models import model_to_dict
import datetime

import logging

log = logging.getLogger('hydro')


###########################################################################
#                            HYDROPONICS VIEWS                            #
#                                                                         #
###########################################################################

def HomeView(request):
    context = {'title': "Home",
               'user': request.user,
               'chemical_setings': ChemicalSettings.objects.get(id=1),
               'waste_setings': WasteSettings.objects.get(id=1)
               }
    return render(request, 'home/home.html', context)


def ErrorView(request):
    context = {'title': "Error",
               }
    return render(request, 'shared/error.html', context)


class ChemicalSettingsView(FormView):
    template_name = 'chemical/chemical.html'
    form_class = ChemicalSettingsForm
    success_url = '/?updated=success'

    def get_initial(self):
        initial = super(ChemicalSettingsView, self).get_initial()
        initial.update(model_to_dict(ChemicalSettings.objects.get(id=1)))
        return initial

    def get_form(self):
        return ChemicalSettingsForm(instance=ChemicalSettings.objects.get(id=1), **self.get_form_kwargs())

    def form_valid(self, form):
        saved = form.save(commit=False)
        ChemicalSettings.objects.filter(pk=1).update(**model_to_dict(saved))
        response = redirect('chemical')
        return response


class WasteSettingsView(FormView):
    template_name = 'waste/waste.html'
    form_class = ChemicalSettingsForm
    success_url = '/?updated=success'

    def get_initial(self):
        initial = super(WasteSettingsView, self).get_initial()
        initial.update(model_to_dict(WasteSettings.objects.get(id=1)))
        return initial

    def get_form(self):
        return WasteSettingsForm(instance=WasteSettings.objects.get(id=1), **self.get_form_kwargs())

    def form_valid(self, form):
        saved = form.save(commit=False)
        WasteSettings.objects.filter(pk=1).update(**model_to_dict(saved))
        response = redirect('waste')
        return response


def ControlEditView(request):
    """

        :param request:
        :return:
    """
    if request.POST:
        form = RequestForm(request.POST)
        if form.is_valid():
            saved = form.save(commit=False)
            saved.save()
            form.save_m2m()
            response = redirect('home')
            response['Location'] += '?requested=success'
            return response
        else:
            log.error(form.errors)
            response = redirect('home')
            response['Location'] += '?requested=failed'
            return response

templates/home/chemical_settings/ORP_reg.html
<div class="sub_section">
    <div class="header">ORP Regulation</div>
    <div class="sub_content">
        <div class="row justify-content-start">
            <div class="col-8 align-self-center">
                <h4>Regulate ORP Automatically</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label switch" for="id_auto_regulate_ORP">
                            {# hidden input to submit false to the form when checkbox is not checked #}
                            <input type="hidden" value="false" name="auto_regulate_ORP"/>
                            <input id="id_auto_regulate_ORP" {% if config.auto_regulate_ORP %} checked {% endif %}
                                   name="auto_regulate_ORP" type="checkbox"><span class="toggle"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>ORP Adjustment Volume</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_ORP_adj_volume">
                            <input id="id_ORP_adj_volume" value="{{config.ORP_adj_volume}}" name="ORP_adj_volume"
                                class="number" max="100" min="0" step=".01" type="number" align="middle" placeholder="mL">
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-12 align-self-center">
                <div class="row justify-content-center">
                    <div class="col-8">
                        <h4>Acceptable ORP Range</h4>
                    </div>
                </div>

                <div class="row justify-content-between">
                    <label class="col-4 form_label" for="id_low_ORP">
                        <input id="id_low_ORP" value="{{config.low_ORP}}" name="low_ORP"
                            class="slider_label" readonly >
                    </label>
                    <label class="col-4 form_label" for="id_high_ORP">
                        <input id="id_high_ORP" value="{{config.high_ORP}}" name="high_ORP"
                            class="slider_label" readonly>
                    </label>
                </div>

                <div class="row">
                    <div class="col">
                        <input id="id_ORP_range" class="data-slider" type="text" data-slider-value="[{{config.low_ORP}}, {{config.high_ORP}}]"
                               data-slider-min="0" data-slider-max="14" data-slider-step=".01"/><br/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/chemical_settings/nutrient_reg.html
<div class="sub_section">
    <div class="header">Nutrient Regulation</div>
    <div class="sub_content">
        <div class="row justify-content-start">
            <div class="col-8 align-self-center">
                <h4>Automatically Regulate Nutrients</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label switch" for="id_auto_regulate_nutrients">
                            {# hidden input to submit false to the form when checkbox is not checked #}
                            <input type="hidden" value="false" name="auto_regulate_nutrients"/>
                            <input id="id_auto_regulate_nutrients" {% if config.auto_regulate_nutrients %} checked {% endif %}
                                   name="auto_regulate_nutrients" type="checkbox"><span class="toggle"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Nutrient Adjustment Volume</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_nutrient_adj_volume"></label>
                        <input id="id_nutrient_adj_volume" value="{{config.nutrient_adj_volume}}" name="nutrient_adj_volume"
                            class="number" max="100" min="0" type="number"  step=".01" align="middle" placeholder="mL">
                    </div>
                </div>
            </div>
            <div class="col-12 align-self-center">
                <div class="row justify-content-center">
                    <div class="col-8">
                        <h4>Acceptable EC Range</h4>
                    </div>
                </div>

                <div class="row justify-content-between">
                    <label class="col-4 form_label" for="id_low_EC">
                        <input id="id_low_EC" value="{{config.low_EC}}" name="low_EC"
                            class="slider_label" readonly >
                    </label>
                    <label class="col-4 form_label" for="id_high_EC">
                        <input id="id_high_EC" value="{{config.high_EC}}" name="high_EC"
                            class="slider_label" readonly>
                    </label>
                </div>

                <div class="row">
                    <div class="col">
                        <input id="id_EC_range" class="data-slider" type="text" data-slider-value="[{{config.low_EC}}, {{config.high_EC}}]"
                               data-slider-min="0" data-slider-max="14" data-slider-step=".01"/><br/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/chemical_settings/pH_reg.html
<div class="sub_section">
    <div class="header">pH Regulation</div>
    <div class="sub_content">
        <div class="row justify-content-start">
            <div class="col-8 align-self-center">
                <h4>Regulate pH Automatically</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label switch" for="id_auto_regulate_pH">
                            {# hidden input to submit false to the form when checkbox is not checked #}
                            <input type="hidden" value="false" name="auto_regulate_pH"/>
                            <input id="id_auto_regulate_pH" {% if config.auto_regulate_pH %} checked {% endif %}
                                   name="auto_regulate_pH" type="checkbox"><span class="toggle"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>pH Adjustment Volume</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_pH_adj_volume">
                            <input id="id_pH_adj_volume" value="{{config.pH_adj_volume}}" name="pH_adj_volume"
                                class="number" max="100" min="0" step=".01" type="number" align="middle" placeholder="mL">
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-12 align-self-center">
                <div class="row justify-content-center">
                    <div class="col-8">
                        <h4>Acceptable pH Range</h4>
                    </div>
                </div>

                <div class="row justify-content-between">
                    <label class="col-4 form_label" for="id_low_pH">
                        <input id="id_low_pH" value="{{config.low_pH}}" name="low_pH"
                            class="slider_label" readonly >
                    </label>
                    <label class="col-4 form_label" for="id_high_pH">
                        <input id="id_high_pH" value="{{config.high_pH}}" name="high_pH"
                            class="slider_label" readonly>
                    </label>
                </div>

                <div class="row">
                    <div class="col">
                        <input id="id_pH_range" class="data-slider" type="text" data-slider-value="[{{config.low_pH}}, {{config.high_pH}}]"
                               data-slider-min="0" data-slider-max="14" data-slider-step=".01"/><br/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/control_panel/data.html
<div class="sub_section">
    <div class="header">Data</div>
    <div class="sub_content">
        <div class="row">
            <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
            <canvas class="graph" id="pHLineChart"></canvas>
            <canvas class="graph" id="ecLineChart"></canvas>
            <canvas class="graph" id="orpLineChart"></canvas>
            <canvas class="graph" id="temperatureLineChart"></canvas>
        </div>
    </div>
</div>

templates/home/home_elements/control.html
{% block status %}
<div class="sub_section current_status">
    <div class="header">Manual Control</div>
    <div class="sub_content clearfix">
    </div>
</div>
{% endblock status %}

templates/home/settings/waste_reg.html
<div class="sub_section">
    <div class="header">Waste Regulation</div>
        <div class="sub_content">
        <div class="row justify-content-start">
            <div class="col-8 align-self-center">
                <h4>Change Water Automatically</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label switch" for="id_auto_water_change">
                            {# hidden input to submit false to the form when checkbox is not checked #}
                            <input type="hidden" value="false" name="auto_water_change"/>
                            <input id="id_auto_water_change" {% if config.auto_water_change %} checked {% endif %}
                                   name="auto_water_change" type="checkbox"><span class="toggle"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Maximum Days Between Water Changes</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_maximum_water_change_interval"></label>
                        <input id="id_maximum_water_change_interval" value="{{config.maximum_water_change_interval}}" name="maximum_water_change_interval"
                            class="number" max="100" min="0" type="number" align="middle" placeholder="days">
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Minimum Days Between Water Changes</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_minimum_water_change_interval"></label>
                        <input id="id_minimum_water_change_interval" value="{{config.minimum_water_change_interval}}" name="minimum_water_change_interval"
                            class="number" max="100" min="0" type="number" align="middle" placeholder="days">
                    </div>
                </div>
            </div>
            <div class="col-12 align-self-center">
                <div class="row justify-content-center">
                    <div class="col-8">
                        <h4>Acceptable ORP Range</h4>
                    </div>
                </div>

                <div class="row justify-content-between">
                    <label class="col-4 form_label" for="id_low_ORP">
                        <input id="id_low_ORP" value="{{config.low_ORP}}" name="low_ORP"
                            class="slider_label" readonly >
                    </label>
                    <label class="col-4 form_label" for="id_high_ORP">
                        <input id="id_high_ORP" value="{{config.high_ORP}}" name="high_ORP"
                            class="slider_label" readonly>
                    </label>
                </div>

                <div class="row">
                    <div class="col">
                        <input id="id_ORP_range" class="data-slider" type="text" data-slider-value="[{{config.low_ORP}}, {{config.high_ORP}}]"
                               data-slider-min="0" data-slider-max="14" data-slider-step=".01"/><br/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/waste_settings/waste_reg.html
<div class="sub_section">
    <div class="header">Waste Regulation</div>
    <div class="sub_content">
        <div class="row justify-content-start">
            <div class="col-8 align-self-center">
                <h4>Change Water Automatically</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label switch" for="id_auto_water_change">
                            {# hidden input to submit false to the form when checkbox is not checked #}
                            <input type="hidden" value="false" name="auto_water_change"/>
                            <input id="id_auto_water_change" {% if config.auto_water_change %} checked {% endif %}
                                   name="auto_water_change" type="checkbox"><span class="toggle"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Resevoir Volume</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_resevoir_volume"></label>
                        <input id="id_resevoir_volume"
                               value="{{config.resevoir_volume}}" name="resevoir_volume"
                            class="number" max="100" min="0" type="number" align="middle" placeholder="L">
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Basin Volume</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_basin_volume"></label>
                        <input id="id_basin_volume" value="{{config.basin_volume}}" name="basin_volume"
                            class="number" max="100" min="0" type="number" align="middle" placeholder="L">
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Maximum Days Between Water Changes</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_maximum_water_change_interval"></label>
                        <input id="id_maximum_water_change_interval" value="{{config.maximum_water_change_interval}}" name="maximum_water_change_interval"
                            class="number" max="100" min="0" type="number" align="middle" placeholder="days">
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Minimum Days Between Water Changes</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_minimum_water_change_interval"></label>
                        <input id="id_minimum_water_change_interval" value="{{config.minimum_water_change_interval}}" name="minimum_water_change_interval"
                            class="number" max="100" min="0" type="number" align="middle" placeholder="days">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/home/waste_settings/water_reg.html
<div class="sub_section">
    <div class="header">Water Regulation</div>
    <div class="sub_content">
        <div class="row justify-content-start">
            <div class="col-8 align-self-center">
                <h4>Pump Automatically</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label switch" for="id_auto_pump">
                            {# hidden input to submit false to the form when checkbox is not checked #}
                            <input type="hidden" value="false" name="auto_pump"/>
                            <input id="id_auto_pump" {% if config.auto_pump %} checked {% endif %}
                                   name="auto_pump" type="checkbox"><span class="toggle"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Refill Automatically</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label switch" for="id_auto_refill">
                            {# hidden input to submit false to the form when checkbox is not checked #}
                            <input type="hidden" value="false" name="auto_refill"/>
                            <input id="id_auto_refill" {% if config.auto_refill %} checked {% endif %}
                                   name="auto_refill" type="checkbox"><span class="toggle"></span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/waste/waste_reg.html
<div class="sub_section">
    <div class="header">Waste Regulation</div>
    <div class="sub_content">
        <div class="row justify-content-start">
            <div class="col-8 align-self-center">
                <h4>Change Water Automatically</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label switch" for="id_auto_water_change">
                            {# hidden input to submit false to the form when checkbox is not checked #}
                            <input type="hidden" value="false" name="auto_water_change"/>
                            <input id="id_auto_water_change" {% if form.auto_water_change.value %} checked {% endif %}
                                   name="auto_water_change" type="checkbox"><span class="toggle"></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Resevoir Volume</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_reservoir_volume">
                            <input id="id_reservoir_volume"
                                   value="{{form.reservoir_volume.value}}" name="reservoir_volume"
                                   class="number" max="100" min="0" type="number" align="middle" placeholder="L">
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Basin Volume</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_basin_volume">
                            <input id="id_basin_volume" value="{{form.basin_volume.value}}" name="basin_volume"
                                   class="number" max="100" min="0" type="number" align="middle" placeholder="L">
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Maximum Days Between Water Changes</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_maximum_water_change_interval">
                            <input id="id_maximum_water_change_interval"
                                   value="{{form.maximum_water_change_interval.value}}"
                                   name="maximum_water_change_interval"
                                   class="number" max="100" min="0" type="number" align="middle" placeholder="days">
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-8 align-self-center">
                <h4>Minimum Days Between Water Changes</h4>
            </div>
            <div class="col-4 align-self-center">
                <div class="row justify-content-center">
                    <div class="col">
                        <label class="form_label" for="id_minimum_water_change_interval">
                            <input id="id_minimum_water_change_interval"
                                   value="{{form.minimum_water_change_interval.value}}"
                                   name="minimum_water_change_interval"
                                   class="number" max="100" min="0" type="number" align="middle" placeholder="days">
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>